python3 main.py --plm='bert' --type='lora' --train_file='datasets/preprocessed/SBERT/SBERT_train_th08.json' --valid_file='datasets/preprocessed/SBERT/SBERT_dev_th08.json' --test_file='datasets/preprocessed/SBERT/SBERT_test_th08.json' > results/230621/SBERT/SBERT_th08_LORA_1.log
python3 main.py --plm='bert' --type='lora' --train_file='datasets/preprocessed/SBERT/SBERT_train_th08.json' --valid_file='datasets/preprocessed/SBERT/SBERT_dev_th08.json' --test_file='datasets/preprocessed/SBERT/SBERT_test_th08.json' > results/230621/SBERT/SBERT_th08_LORA_2.log
python3 main.py --plm='bert' --type='lora' --train_file='datasets/preprocessed/SBERT/SBERT_train_th08.json' --valid_file='datasets/preprocessed/SBERT/SBERT_dev_th08.json' --test_file='datasets/preprocessed/SBERT/SBERT_test_th08.json' > results/230621/SBERT/SBERT_th08_LORA_3.log
python3 main.py --plm='bert' --type='lora' --train_file='datasets/preprocessed/SBERT/SBERT_train_th08.json' --valid_file='datasets/preprocessed/SBERT/SBERT_dev_th08.json' --test_file='datasets/preprocessed/SBERT/SBERT_test_th08.json' > results/230621/SBERT/SBERT_th08_LORA_4.log
python3 main.py --plm='bert' --type='lora' --train_file='datasets/preprocessed/SBERT/SBERT_train_th08.json' --valid_file='datasets/preprocessed/SBERT/SBERT_dev_th08.json' --test_file='datasets/preprocessed/SBERT/SBERT_test_th08.json' > results/230621/SBERT/SBERT_th08_LORA_5.log

python3 main.py --plm='bert' --type='lora'  --train_file='datasets/preprocessed/prompt/prompt_train_claim_sent_th08.json' --valid_file='datasets/preprocessed/prompt/prompt_dev_claim_sent_th08.json' --test_file='datasets/preprocessed/prompt/prompt_test_claim_sent_th08.json' > results/230621/prompt/prompt_th08_LORA_1.log
python3 main.py --plm='bert' --type='lora'  --train_file='datasets/preprocessed/prompt/prompt_train_claim_sent_th08.json' --valid_file='datasets/preprocessed/prompt/prompt_dev_claim_sent_th08.json' --test_file='datasets/preprocessed/prompt/prompt_test_claim_sent_th08.json' > results/230621/prompt/prompt_th08_LORA_2.log
python3 main.py --plm='bert' --type='lora'  --train_file='datasets/preprocessed/prompt/prompt_train_claim_sent_th08.json' --valid_file='datasets/preprocessed/prompt/prompt_dev_claim_sent_th08.json' --test_file='datasets/preprocessed/prompt/prompt_test_claim_sent_th08.json' > results/230621/prompt/prompt_th08_LORA_3.log
python3 main.py --plm='bert' --type='lora'  --train_file='datasets/preprocessed/prompt/prompt_train_claim_sent_th08.json' --valid_file='datasets/preprocessed/prompt/prompt_dev_claim_sent_th08.json' --test_file='datasets/preprocessed/prompt/prompt_test_claim_sent_th08.json' > results/230621/prompt/prompt_th08_LORA_4.log
python3 main.py --plm='bert' --type='lora'  --train_file='datasets/preprocessed/prompt/prompt_train_claim_sent_th08.json' --valid_file='datasets/preprocessed/prompt/prompt_dev_claim_sent_th08.json' --test_file='datasets/preprocessed/prompt/prompt_test_claim_sent_th08.json' > results/230621/prompt/prompt_th08_LORA_5.log


#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/train.json' --valid_file='datasets/preprocessed/dev.json' --test_file='datasets/preprocessed/test.json' > results/230614/gold/bert/gold_LORA_1.log
#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/train.json' --valid_file='datasets/preprocessed/dev.json' --test_file='datasets/preprocessed/test.json' > results/230614/gold/bert/gold_LORA_2.log
#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/train.json' --valid_file='datasets/preprocessed/dev.json' --test_file='datasets/preprocessed/test.json' > results/230614/gold/bert/gold_LORA_3.log
#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/train.json' --valid_file='datasets/preprocessed/dev.json' --test_file='datasets/preprocessed/test.json' > results/230614/gold/bert/gold_LORA_4.log
#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/train.json' --valid_file='datasets/preprocessed/dev.json' --test_file='datasets/preprocessed/test.json' > results/230614/gold/bert/gold_LORA_5.log
#
#python3 main.py --plm='ernie' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/train.json' --valid_file='datasets/preprocessed/dev.json' --test_file='datasets/preprocessed/test.json' > results/230614/gold/ernie/gold_LORA_1.log
#python3 main.py --plm='ernie' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/train.json' --valid_file='datasets/preprocessed/dev.json' --test_file='datasets/preprocessed/test.json' > results/230614/gold/ernie/gold_LORA_2.log
#python3 main.py --plm='ernie' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/train.json' --valid_file='datasets/preprocessed/dev.json' --test_file='datasets/preprocessed/test.json' > results/230614/gold/ernie/gold_LORA_3.log
#python3 main.py --plm='ernie' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/train.json' --valid_file='datasets/preprocessed/dev.json' --test_file='datasets/preprocessed/test.json' > results/230614/gold/ernie/gold_LORA_4.log
#python3 main.py --plm='ernie' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/train.json' --valid_file='datasets/preprocessed/dev.json' --test_file='datasets/preprocessed/test.json' > results/230614/gold/ernie/gold_LORA_5.log

#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/prompt/prompt_train_claim_sent_th08.json' --valid_file='datasets/preprocessed/prompt/prompt_dev_claim_sent_th08.json' --test_file='datasets/preprocessed/prompt/prompt_test_claim_sent_th08.json' > results/230614/prompt/prompt_th08_LORA_1.log
#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/hybrid/hybrid_train.json' --valid_file='datasets/preprocessed/hybrid/hybrid_dev.json' --test_file='datasets/preprocessed/hybrid/hybrid_test.json' > results/230614/hybrid/hybrid_LORA_1.log
#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/surface/surface_train.json' --valid_file='datasets/preprocessed/surface/surface_dev.json' --test_file='datasets/preprocessed/surface/surface_test.json' > results/230614/surface/surface_LORA_1.log
#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/semantic/semantic_train.json' --valid_file='datasets/preprocessed/semantic/semantic_dev.json' --test_file='datasets/preprocessed/semantic/semantic_test.json' > results/230614/semantic/semantic_LORA_1.log



#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/prompt/prompt_train_claim_sent_th08.json' --valid_file='datasets/preprocessed/prompt/prompt_dev_claim_sent_th08.json' --test_file='datasets/preprocessed/prompt/prompt_test_claim_sent_th08.json' > results/230614/prompt/prompt_th08_LORA_2.log
#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/prompt/prompt_train_claim_sent_th08.json' --valid_file='datasets/preprocessed/prompt/prompt_dev_claim_sent_th08.json' --test_file='datasets/preprocessed/prompt/prompt_test_claim_sent_th08.json' > results/230614/prompt/prompt_th08_LORA_3.log
#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/prompt/prompt_train_claim_sent_th08.json' --valid_file='datasets/preprocessed/prompt/prompt_dev_claim_sent_th08.json' --test_file='datasets/preprocessed/prompt/prompt_test_claim_sent_th08.json' > results/230614/prompt/prompt_th08_LORA_4.log
#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/prompt/prompt_train_claim_sent_th08.json' --valid_file='datasets/preprocessed/prompt/prompt_dev_claim_sent_th08.json' --test_file='datasets/preprocessed/prompt/prompt_test_claim_sent_th08.json' > results/230614/prompt/prompt_th08_LORA_5.log
#
#python3 main.py --plm='bert' --type='lora'  --lr=5e-6 --train_file='datasets/preprocessed/hybrid/hybrid_train.json' --valid_file='datasets/preprocessed/hybrid/hybrid_dev.json' --test_file='datasets/preprocessed/hybrid/hybrid_test.json' > results/230614/hybrid/hybrid_LORA_2.log
#python3 main.py --plm='bert' --type='lora'  --lr=5e-6 --train_file='datasets/preprocessed/hybrid/hybrid_train.json' --valid_file='datasets/preprocessed/hybrid/hybrid_dev.json' --test_file='datasets/preprocessed/hybrid/hybrid_test.json' > results/230614/hybrid/hybrid_LORA_3.log
#python3 main.py --plm='bert' --type='lora'  --lr=5e-6 --train_file='datasets/preprocessed/hybrid/hybrid_train.json' --valid_file='datasets/preprocessed/hybrid/hybrid_dev.json' --test_file='datasets/preprocessed/hybrid/hybrid_test.json' > results/230614/hybrid/hybrid_LORA_4.log
#python3 main.py --plm='bert' --type='lora'  --lr=5e-6 --train_file='datasets/preprocessed/hybrid/hybrid_train.json' --valid_file='datasets/preprocessed/hybrid/hybrid_dev.json' --test_file='datasets/preprocessed/hybrid/hybrid_test.json' > results/230614/hybrid/hybrid_LORA_5.log
#
#
#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/surface/surface_train.json' --valid_file='datasets/preprocessed/surface/surface_dev.json' --test_file='datasets/preprocessed/surface/surface_test.json' > results/230614/surface/surface_LORA_2.log
#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/surface/surface_train.json' --valid_file='datasets/preprocessed/surface/surface_dev.json' --test_file='datasets/preprocessed/surface/surface_test.json' > results/230614/surface/surface_LORA_3.log
#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/surface/surface_train.json' --valid_file='datasets/preprocessed/surface/surface_dev.json' --test_file='datasets/preprocessed/surface/surface_test.json' > results/230614/surface/surface_LORA_4.log
#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/surface/surface_train.json' --valid_file='datasets/preprocessed/surface/surface_dev.json' --test_file='datasets/preprocessed/surface/surface_test.json' > results/230614/surface/surface_LORA_5.log
#
#python3 main.py --plm='bert' --type='lora'  --lr=5e-6 --train_file='datasets/preprocessed/semantic/semantic_train.json' --valid_file='datasets/preprocessed/semantic/semantic_dev.json' --test_file='datasets/preprocessed/semantic/semantic_test.json' > results/230614/semantic/semantic_LORA_2.log
#python3 main.py --plm='bert' --type='lora'  --lr=5e-6 --train_file='datasets/preprocessed/semantic/semantic_train.json' --valid_file='datasets/preprocessed/semantic/semantic_dev.json' --test_file='datasets/preprocessed/semantic/semantic_test.json' > results/230614/semantic/semantic_LORA_3.log
#python3 main.py --plm='bert' --type='lora'  --lr=5e-6 --train_file='datasets/preprocessed/semantic/semantic_train.json' --valid_file='datasets/preprocessed/semantic/semantic_dev.json' --test_file='datasets/preprocessed/semantic/semantic_test.json' > results/230614/semantic/semantic_LORA_4.log
#python3 main.py --plm='bert' --type='lora'  --lr=5e-6 --train_file='datasets/preprocessed/semantic/semantic_train.json' --valid_file='datasets/preprocessed/semantic/semantic_dev.json' --test_file='datasets/preprocessed/semantic/semantic_test.json' > results/230614/semantic/semantic_LORA_5.log
#
#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/prompt/prompt_train_claim_sent_out5.json' --valid_file='datasets/preprocessed/prompt/prompt_dev_claim_sent_out5.json' --test_file='datasets/preprocessed/prompt/prompt_test_claim_sent_out5.json' > results/230614/prompt/prompt_out5_LORA_1.log
#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/prompt/prompt_train_claim_sent_out5.json' --valid_file='datasets/preprocessed/prompt/prompt_dev_claim_sent_out5.json' --test_file='datasets/preprocessed/prompt/prompt_test_claim_sent_out5.json' > results/230614/prompt/prompt_out5_LORA_2.log
#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/prompt/prompt_train_claim_sent_out5.json' --valid_file='datasets/preprocessed/prompt/prompt_dev_claim_sent_out5.json' --test_file='datasets/preprocessed/prompt/prompt_test_claim_sent_out5.json' > results/230614/prompt/prompt_out5_LORA_3.log
#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/prompt/prompt_train_claim_sent_out5.json' --valid_file='datasets/preprocessed/prompt/prompt_dev_claim_sent_out5.json' --test_file='datasets/preprocessed/prompt/prompt_test_claim_sent_out5.json' > results/230614/prompt/prompt_out5_LORA_4.log
#python3 main.py --plm='bert' --type='lora' --lr=5e-6 --train_file='datasets/preprocessed/prompt/prompt_train_claim_sent_out5.json' --valid_file='datasets/preprocessed/prompt/prompt_dev_claim_sent_out5.json' --test_file='datasets/preprocessed/prompt/prompt_test_claim_sent_out5.json' > results/230614/prompt/prompt_out5_LORA_5.log
